In [9]:
#Import the Libraries
import numpy as np
import pandas as pd
import matplotlib as plt
import math

from sklearn import linear_model
df =pd.read_csv("Car.csv")
df

Mileage  Age  SellPrice
0     69000    6      18000
1     35000    3      34000
2     57000    5      26100
3     22500    2      40000
4     46000    4      31500
5     59000    5      26750
6     52000    5      32000
7     72000    6      19300
8     91000    8      12000
9     67000    6      22000
10    83000    7      18700
11    79000    7      19500
12    59000    5      26000
13    58780    4      27500
14    82450    7      19400
15    25400    3      35000
16    28000    2      35500
17    69000    5      19700
18    87600    8      12800
19    52000    5      28200

In [10]:
#y denotes Selling Price
#X denotes the Mileage and Age

X = df [[ 'Mileage', 'Age']]
y = df [['SellPrice']]

model = linear_model.LinearRegression()
model.fit(X,y)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
#Find the coefficients 
model.coef_

array([[-3.38301880e-01, -3.52792012e+02]])

In [12]:
#Find the intercept
model.intercept_

array([47223.34910508])

In [13]:
#My Prediction
#Mileage = 100,000
#Age = 10
model.predict([[100000, 10]])

array([[9865.241004]])